"""Skill definitions — prompt templates and parameter schemas."""

from __future__ import annotations

from app.models import SkillDef

# ─────────────────────────────────────────────────────────
# Skill Registry — add new skills here.
# ─────────────────────────────────────────────────────────

SKILLS: dict[str, SkillDef] = {
    "lesson-plan": SkillDef(
        name="lesson-plan",
        display_name="수업지도안",
        description="차시별 교수학습과정안을 생성합니다. 학습목표, 도입/전개/정리, 평가계획, 준비물을 포함합니다.",
        category="수업",
        icon="📖",
        params=[
            {
                "key": "school_level",
                "label": "학교급",
                "type": "select",
                "required": True,
                "options": ["초등", "중학교", "고등학교"],
            },
            {
                "key": "grade",
                "label": "학년",
                "type": "text",
                "required": True,
                "placeholder": "예: 3학년",
            },
            {
                "key": "subject",
                "label": "과목",
                "type": "select",
                "required": True,
                "options": [
                    "국어", "수학", "과학", "영어", "사회", "역사",
                    "체육", "음악", "미술", "기술·가정", "정보", "도덕",
                ],
            },
            {
                "key": "unit",
                "label": "단원명",
                "type": "text",
                "required": True,
                "placeholder": "예: 3. 광합성과 식물의 호흡",
            },
            {
                "key": "lesson_number",
                "label": "차시",
                "type": "text",
                "required": True,
                "placeholder": "예: 3/15",
            },
            {
                "key": "learning_objectives",
                "label": "학습목표 (선택)",
                "type": "textarea",
                "required": False,
                "placeholder": "구체적인 학습목표가 있다면 입력하세요. 비워두면 AI가 생성합니다.",
            },
            {
                "key": "style_hint",
                "label": "수업 스타일",
                "type": "select",
                "required": False,
                "options": [
                    "실험·탐구 중심",
                    "강의식",
                    "토론·프로젝트 중심",
                    "게임·활동 중심",
                    "특별히 없음",
                ],
            },
            {
                "key": "extra_notes",
                "label": "추가 요청사항",
                "type": "textarea",
                "required": False,
                "placeholder": "특별히 포함하고 싶은 활동, 참고자료, 주의사항 등이 있다면 입력하세요.",
            },
        ],
    ),
    "parent-letter": SkillDef(
        name="parent-letter",
        display_name="가정통신문",
        description="학부모 발송용 가정통신문을 생성합니다. 행사안내, 설문, 동의서 등 다양한 유형을 지원합니다.",
        category="소통",
        icon="📧",
        params=[
            {
                "key": "school_level",
                "label": "학교급",
                "type": "select",
                "required": True,
                "options": ["초등", "중학교", "고등학교"],
            },
            {
                "key": "grade",
                "label": "학년",
                "type": "text",
                "required": True,
                "placeholder": "예: 3학년",
            },
            {
                "key": "letter_type",
                "label": "통신문 유형",
                "type": "select",
                "required": True,
                "options": [
                    "행사 안내",
                    "현장체험학습 안내",
                    "설문 조사",
                    "동의서/신청서",
                    "상담 안내",
                    "건강/안전 안내",
                    "교육과정 설명회",
                    "학부모 총회",
                    "방학 생활 안내",
                    "기타 안내",
                ],
            },
            {
                "key": "title",
                "label": "제목",
                "type": "text",
                "required": True,
                "placeholder": "예: 2026학년도 1학기 현장체험학습 안내",
            },
            {
                "key": "event_date",
                "label": "행사일 / 기한",
                "type": "text",
                "required": False,
                "placeholder": "예: 2026년 7월 15일 (수) 09:00~12:30",
            },
            {
                "key": "location",
                "label": "장소",
                "type": "text",
                "required": False,
                "placeholder": "예: 국립중앙과학관",
            },
            {
                "key": "recipient",
                "label": "대상",
                "type": "text",
                "required": False,
                "placeholder": "예: 3학년 2반 학부모님",
            },
            {
                "key": "extra_notes",
                "label": "추가 요청사항",
                "type": "textarea",
                "required": False,
                "placeholder": "준비물, 참가비, 신청 마감일 등 특별히 포함할 내용을 입력하세요.",
            },
        ],
    ),
    "assessment": SkillDef(
        name="assessment",
        display_name="평가문항",
        description="단원별 평가문항을 출제합니다. 객관식, 서술형, 논술형 문항과 채점 기준표를 포함합니다.",
        category="평가",
        icon="📝",
        params=[
            {
                "key": "school_level",
                "label": "학교급",
                "type": "select",
                "required": True,
                "options": ["초등", "중학교", "고등학교"],
            },
            {
                "key": "grade",
                "label": "학년",
                "type": "text",
                "required": True,
                "placeholder": "예: 2학년",
            },
            {
                "key": "subject",
                "label": "과목",
                "type": "select",
                "required": True,
                "options": [
                    "국어", "수학", "과학", "영어", "사회", "역사",
                    "체육", "음악", "미술", "기술·가정", "정보", "도덕",
                ],
            },
            {
                "key": "unit",
                "label": "단원명",
                "type": "text",
                "required": True,
                "placeholder": "예: 3. 광합성과 식물의 호흡",
            },
            {
                "key": "question_type",
                "label": "문항 유형",
                "type": "select",
                "required": True,
                "options": [
                    "객관식",
                    "서술형",
                    "혼합 (객관식 + 서술형)",
                ],
            },
            {
                "key": "question_count",
                "label": "문항 수",
                "type": "number",
                "required": True,
                "placeholder": "예: 10",
            },
            {
                "key": "difficulty_hint",
                "label": "난이도 배분",
                "type": "select",
                "required": False,
                "options": [
                    "기본 비율 (하30/중50/상20)",
                    "쉽게 (하50/중40/상10)",
                    "어렵게 (하10/중50/상40)",
                    "내신 대비 (하20/중40/상40)",
                ],
            },
            {
                "key": "focus_areas",
                "label": "중점 평가 영역 (선택)",
                "type": "textarea",
                "required": False,
                "placeholder": "특별히 평가하고 싶은 개념이나 역량이 있다면 입력하세요.",
            },
            {
                "key": "extra_notes",
                "label": "추가 요청사항",
                "type": "textarea",
                "required": False,
                "placeholder": "특별한 출제 방침, 포함/제외할 내용, 참고자료 등이 있다면 입력하세요.",
            },
        ],
    ),
    "admin-doc": SkillDef(
        name="admin-doc",
        display_name="행정문서",
        description="학교 업무용 행정문서를 생성합니다. 사업계획서, 결과보고서, 예산계획, 업무분장 등 다양한 행정 양식을 지원합니다.",
        category="행정",
        icon="📋",
        params=[
            {
                "key": "school_level",
                "label": "학교급",
                "type": "select",
                "required": True,
                "options": ["초등", "중학교", "고등학교"],
            },
            {
                "key": "doc_type",
                "label": "문서 유형",
                "type": "select",
                "required": True,
                "options": [
                    "사업 계획서",
                    "결과 보고서",
                    "예산 계획서",
                    "업무 분장표",
                    "연간 운영 계획",
                    "교내 연수 계획",
                    "위원회 운영 계획",
                    "행사 기획안",
                    "공문 (대내외)",
                    "기타 양식",
                ],
            },
            {
                "key": "title",
                "label": "문서 제목",
                "type": "text",
                "required": True,
                "placeholder": "예: 2026학년도 과학의 날 행사 운영 계획",
            },
            {
                "key": "start_date",
                "label": "추진 기간",
                "type": "text",
                "required": False,
                "placeholder": "예: 2026년 3월 ~ 2026년 7월",
            },
            {
                "key": "target_audience",
                "label": "대상",
                "type": "text",
                "required": False,
                "placeholder": "예: 전교생, 1학년 전체",
            },
            {
                "key": "budget_hint",
                "label": "예산 정보 (선택)",
                "type": "text",
                "required": False,
                "placeholder": "예: 총 1,500,000원 (학교예산)",
            },
            {
                "key": "extra_notes",
                "label": "추가 요청사항",
                "type": "textarea",
                "required": False,
                "placeholder": "특별히 포함할 내용, 결재 라인, 첨부 서류 등이 있다면 입력하세요.",
            },
        ],
    ),
}
